import json
from openai import OpenAI
from dotenv import load_dotenv
import os


load_dotenv()

client = OpenAI(
  api_key = os.getenv("OPENAI_API_KEY")
)

def generate_cover_letter(
  resume_text: str, profile: dict, job_description: str
)-> str:
  prompt = f"""
  Understand this scenario supposedly You are a normal human being who views candidate's resume when someone mails them, you yourself dont like autogenerated cover letters as AI is too much everywhere AI is inserted in every field 
  You keep this thing in mind
  and as a expert technical recruiter and career coach youll write a cover letter for me based on the resume and job description provided below
  
  Candidate's Profile:
  
  {json.dumps(profile, indent=2)}
  
  Job Description:
  
  {job_description}
  
  TASK:
  
  Generate a highly personalized cover letter.

  Rules:

  - Use ONLY information from the resume and candidate profile.
  - Never invent skills, projects, internships, certifications, or achievements.
  - Match existing skills and projects to the job requirements.
  - Mention relevant projects when useful.
  - Sound professional but human.
  - Sound like a graduated engineering student.
  - Avoid corporate buzzwords.

  Never use:

  - I am excited to apply
  - I am thrilled to apply
  - I am passionate about
  - Dynamic professional
  - Leveraging my skills

  Use varied sentence structures.

  Keep it under 250 words.

  Output ONLY the cover letter.
  """
  response = client.chat.completions.create(
    model="gpt-4o",
    temperature=0.3,
    messages=[
      {"role": "user", "context": prompt}
    ]
  )
  return response.choices[0].message.content.strip()

